version: '3'

services: 
  jenkins:
    image: jenkins/jenkins:lts
    ports: 
        - '8081:8080'
        - '5001:50000'
    container_name: jenkins-bank
    networks: 
      - dev_network_bank
    privileged: true
    volumes: 
        - jenkins_home:/var/jenkins_home 

  db:
    image: mysql:8.0
    container_name: db_mysql_bank
    volumes: 
      - db_data:/var/lib/mysql
    restart:  always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    networks: 
      - dev_network_bank
    ports:
      - '3307:3306'

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin:5.1
    container_name: phpmyadmin_bank
    restart:  always
    ports:
      - '8082:80'
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    networks: 
      - dev_network_bank



volumes:
  jenkins_home:
  db_data:
networks: 
  dev_network_bank:    
  