# https://docs.docker.com/compose/compose-file/
version: '3'

services:
  db:
    image: mysql:8.0
    #container_name: test1_db
    volumes: 
      - db_data:/var/lib/mysql
    restart:  always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    networks: 
      - dev_network
    ports:
      - '3307:3306'

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin:5.1
    #container_name: test1_mysql
    restart:  always
    ports:
      - '8080:80'
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    networks: 
      - dev_network


  ## node:
  ##   image: node:14.8.0-alpine 
    #container_name: test1_mysql
  ##  restart:  always

volumes:
  db_data:

networks: 
  dev_network:

